name: mamba
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - einops>=0.8
      - numpy<2
      - pillow
      - ninja
      - transformers==4.51.3
      - huggingface-hub==0.36.0
      - tqdm
